PLAYDATE_SDK_PATH=/opt/playdate-sdk

trackzzzz.pdx: source/bitmore.fnt source/*
	pdc --verbose source trackzzzz.pdx

source/bitmore.fnt:
	cp $(PLAYDATE_SDK_PATH)/Resources/Fonts/Bitmore/font-Bitmore.fnt source/bitmore.fnt
	cp $(PLAYDATE_SDK_PATH)/Resources/Fonts/Bitmore/font-Bitmore-table-7-11.png source/bitmore-table-7-11.png
