#!/bin/bash

IMAGE_VIEWER="${IMAGE_VIEWER:-xdg-open}"
$IMAGE_VIEWER example.ppm&

git ls-files -co '*.cpp' '*.h' | entr -c -r -s 'echo compile && make tinytrace && echo run && ./tinytrace example.ppm continue; echo exit status $?'
