#!/bin/bash

IMAGE_VIEWER="${IMAGE_VIEWER:-xdg-open}"
$IMAGE_VIEWER example.ppm&

git ls-files -co '*.cpp' '*.h' | entr -c -r -s 'clang++ -O3 -march=native tinytrace.cpp ray.cpp -o tinytrace && ./tinytrace example.ppm continue; echo exit status $?'
